server:
  port: 81
spring:
  application:
    name: auth-svc
  profiles:
    include: consul,jwt
  redis:
    host: 43.142.4.243
    port: 6379
    database: 0
    timeout: 3000
    password: 'yanh' # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 2 # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-wait: -1ms # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-idle: 1 # 连接池中的最大空闲连接 默认为8
        min-idle: 0 # 连接池中的最小空闲连接 默认为 0
