spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        service-name: ${spring.application.name}
        instanceId: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
        tags: auth-svc
        healthCheckInterval: 15s
