server:
  port: 80

spring:
  application:
    name: gateway-svc
  profiles:
    include: consul,gw,jwt
  redis:
    host: 43.142.4.243
    port: 6379
    password: 'yanh' # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 2 # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-wait: -1ms # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-idle: 1 # 连接池中的最大空闲连接 默认为8
        min-idle: 0 # 连接池中的最小空闲连接 默认为 0

#gateway提供路由访问规则列表的web界面,但是默认是关闭的,如果想要查看服务路由规则可以在配置文件中开启
management:
  endpoints:
    web:
      exposure:
        include: '*' # 需要开放的端点，默认只开放 health 和 info 两个端点，通过 * 开放所有的端点。
  endpoint:
    health:
      enabled: true  # 是否开启， 默认true 开启
      show-details: always
